language: swift
osx_image: xcode10.2
before_install:
- set -o pipefail
- xcrun simctl boot "iPhone 8" || echo "(Pre)Launched the simulator."
- pod repo update
script:
- bundle install
- bundle exec fastlane build